safe_arm:
  l_arm_joint_controller:
    type: "effort_controllers/JointTrajectoryController"
    joints:
      - l_shoulder_yaw_joint
      - l_shoulder_pitch_joint
      - l_shoulder_roll_joint
      - l_underarm_joint
      - l_elbow_pitch_joint
      - l_elbow_yaw_joint
      - l_wrist_pitch_joint
      - l_wrist_roll_joint

    gains:
      l_shoulder_yaw_joint:   {p: 1500.0, i: 0.0, d: 0.1, i_clamp: 0.0}
      l_shoulder_pitch_joint: {p: 1500.0, i: 0.0, d: 0.1, i_clamp: 0.0}
      l_shoulder_roll_joint:  {p: 1500.0, i: 0.0, d: 0.1, i_clamp: 0.0}
      l_underarm_joint:       {p: 1500.0, i: 0.0, d: 0.1, i_clamp: 0.0}
      l_elbow_pitch_joint:    {p: 1500.0, i: 0.0, d: 0.1, i_clamp: 0.0}
      l_elbow_yaw_joint:      {p: 1500.0, i: 0.0, d: 0.1, i_clamp: 0.0}
      l_wrist_pitch_joint:    {p: 1500.0, i: 0.0, d: 0.1, i_clamp: 0.0}
      l_wrist_roll_joint:     {p: 1500.0, i: 0.0, d: 0.1, i_clamp: 0.0}