safe_arm:
  l_shoulder_yaw_joint_controller:
    type: effort_controllers/JointPositionController
    joint: l_shoulder_yaw_joint
    pid: {p: 10.0, i: 0.04, d: 1.0, i_clamp_max: 100, i_clamp_min: -100}

  l_shoulder_pitch_joint_controller:
    type: effort_controllers/JointPositionController
    joint: l_shoulder_pitch_joint
    pid: {p: 5.0, i: 0.04, d: 1.0, i_clamp_max: 100, i_clamp_min: -100}

  l_shoulder_roll_joint_controller:
    type: effort_controllers/JointPositionController
    joint: l_shoulder_roll_joint
    pid: {p: 30.0, i: 0.5, d: 5.0, i_clamp_max: 100, i_clamp_min: -100}

  l_underarm_joint_controller:
    type: effort_controllers/JointPositionController
    joint: l_underarm_joint
    pid: {p: 2.0, i: 0.01, d: 0.2, i_clamp_max: 100, i_clamp_min: -100}

  l_elbow_pitch_joint_controller:
    type: effort_controllers/JointPositionController
    joint: l_elbow_pitch_joint
    pid: {p: 30.0, i: 0.5, d: 5.0, i_clamp_max: 100, i_clamp_min: -100}

  l_elbow_yaw_joint_controller:
    type: effort_controllers/JointPositionController
    joint: l_elbow_yaw_joint
    pid: {p: 2.0, i: 0.01, d: 0.2, i_clamp_max: 100, i_clamp_min: -100}

  l_wrist_pitch_joint_controller:
    type: effort_controllers/JointPositionController
    joint: l_wrist_pitch_joint
    pid: {p: 2.0, i: 0.01, d: 0.2, i_clamp_max: 100, i_clamp_min: -100}

  l_wrist_roll_joint_controller:
    type: effort_controllers/JointPositionController
    joint: l_wrist_roll_joint
    pid: {p: 2.0, i: 0.01, d: 0.2, i_clamp_max: 100, i_clamp_min: -100}
