safe_arm:
  r_arm_joint_controller:
    type: "effort_controllers/JointTrajectoryController"
    joints:
      - r_shoulder_yaw_joint
      - r_shoulder_pitch_joint
      - r_shoulder_roll_joint
      - r_underarm_joint
      - r_elbow_pitch_joint
      - r_elbow_yaw_joint
      - r_wrist_pitch_joint
      - r_wrist_roll_joint

    gains:
      r_shoulder_yaw_joint:   {p: 1000.0, i: 0.0, d: 0.1, i_clamp: 0.0}
      r_shoulder_pitch_joint: {p: 1000.0, i: 0.0, d: 0.1, i_clamp: 0.0}
      r_shoulder_roll_joint:  {p: 1000.0, i: 0.0, d: 0.1, i_clamp: 0.0}
      r_underarm_joint:       {p: 1000.0, i: 0.0, d: 0.1, i_clamp: 0.0}
      r_elbow_pitch_joint:    {p: 1000.0, i: 0.0, d: 0.1, i_clamp: 0.0}
      r_elbow_yaw_joint:      {p: 1000.0, i: 0.0, d: 0.1, i_clamp: 0.0}
      r_wrist_pitch_joint:    {p: 1000.0, i: 0.0, d: 0.1, i_clamp: 0.0}
      r_wrist_roll_joint:     {p: 1000.0, i: 0.0, d: 0.1, i_clamp: 0.0}